version: '3.8'
services:
  postgres:
      image: postgres:14-alpine
      ports:
        - 5432:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=root
        - POSTGRES_DB=flightDB
        - POSTGRES_GDATA=/data/postgres
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d flightDB -U root"]
        timeout: 5s
        retries: 10
      networks:
        - uddanNetwork
volumes:
  postgres-data:


networks:
  uddanNetwork:

